# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

app.fishbowl.ready:
    path: /fishbowl-status/{slug}
    controller: App\Controller\FishbowlController::status
    methods: [GET]

app.fishbowl.participants:
    path: /fishbowl-participants/{slug}
    controller: App\Controller\FishbowlController::participants
    methods: [GET]

app.fishbowl.ping:
    path: /ping/{slug}
    controller: App\Controller\FishbowlController::ping
    methods: [POST]

app.fishbowl.private:
    path: /private-password/{slug}
    controller: App\Controller\FishbowlController::private
    methods: [POST]

app.fishbowl.world_cafe:
    path: /world-cafe
    controller: App\Controller\FishbowlController::world
    methods: [GET]
    defaults:   { _feature: 'world_cafe' }
