# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

symfonycasts_reset_password:
    request_password_repository: App\Core\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 60
    enable_garbage_collection: true
