# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

framework:
    default_locale: "%locale%"
    translator:
        default_path: "%kernel.project_dir%/translations"
        fallbacks:
            - "%locale%"
