# This file is part of the Stooa codebase.
#
# (c) 2020 - present Runroom SL
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This workflow will check if the Developer Certificate os Origin is signed

name: Developer Certificate of Origin (DCO)

on:
    issue_comment:
        types: [created]

    pull_request_target:
        types: [opened, closed, synchronize]

jobs:
    signature:
        name: Signature

        runs-on: ubuntu-latest

        steps:
            - name: Check Developer Certificate of Origin is signed
              if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the DCO Document and I hereby sign the DCO') || github.event_name == 'pull_request_target'
              uses: cla-assistant/github-action@v2.1.3-beta
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              with:
                  path-to-signatures: signatures/version1/dco.json
                  path-to-document: https://github.com/Stooa/Stooa/blob/main/DCOLICENSE
                  branch: main
                  remote-organization-name: Stooa
                  remote-repository-name: DCO-signatures
                  use-dco-flag: true
                  create-file-commit-message: 'Creating file for storing DCO Signatures'
                  signed-commit-message: '$contributorName has signed the DCO in #$pullRequestNo'
                  custom-allsigned-prcomment: '**DCO Assistant** All Contributors have signed the DCO. üìù ‚úÖ '
                  allowlist: stooa-dev,weblate,renovate-bot,renovate[bot]
